# stage 1 - build stage will produce the dist folder

FROM node:18-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build # /app/dist



# stage 2 - production stage will copy the dist folder and run the app using nginx

FROM nginx:alpine

# Copy the built dist folder from the builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy the nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]